CREATE DATABASE IF NOT EXISTS gvt;
CREATE DATABASE IF NOT EXISTS gvt_account;
CREATE USER IF NOT EXISTS 'gvt'@'%' IDENTIFIED BY 'db_password';
GRANT ALL PRIVILEGES ON gvt.* TO 'gvt'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON gvt_account.* TO 'gvt'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;